const propsPriority = {
  position: 0,
  top: 1,
  bottom: 2,
  left: 3,
  right: 4,
  "z-index": 5,
  overflow: 6,
  "box-sizing": 7,
  display: 8,
  flex: 9,
  "flex-direction": 10,
  "flex-wrap": 11,
  "flex-grow": 12,
  "align-items": 13,
  "justify-content": 14,
  grid: 15,
  "grid-template-columns": 16,
  "grid-template-rows": 17,
  gap: 18,
  width: 19,
  height: 20,
  padding: 21,
  "padding-top": 22,
  "padding-bottom": 23,
  "padding-left": 24,
  "padding-right": 25,
  margin: 26,
  "margin-top": 27,
  "margin-bottom": 28,
  "margin-left": 29,
  "margin-right": 30,
  border: 31,
  "border-radius": 32,
  background: 33,
  color: 34,
  opacity: 35,
  "user-select": 36,
  "font-family": 37,
  "font-size": 38,
  "line-height": 39,
  "text-align": 40,
  "text-decoration": 41,
  "text-overflow": 42,
  cursor: 43,
  visibility: 44,
  tranform: 45,
  transition: 46,
  animation: 47,
};

module.exports = {
  propsPriority,
};
